### ISSUE TITLE
Tourism report: feedback from Open Data unit

### ISSUE THREAD

**Issue by asRodelgo** [asRodelgo/reportGenerator360#6]
- Reach out to Tourism folks to get a better explanation for some indicators. Can be in the shape of subtitles, or other. Report may be clear for Tourism experts but not for general public

**Comment by mrpsonglao** [comment]
**Update as of 14 August 2017:** Asked JM (Tourism) for help in providing better but concise explanations for Tourism indicators, to make it understandable for general public

Still waiting for his updates as of today (Aug. 18 (Fri), 2017).

**Comment by mrpsonglao** [comment]
Addressed this issue via pull request #9
